apiVersion: v1
kind: Secret
metadata:
  name: sadi-secrets
  namespace: sadi-system
type: Opaque
data:
  # Replace these values with the base64 encoded secrets
  # Example: echo -n 'your_secret_here' | base64
  secret_key: "YV9zdXBlcl9zZWNyZXRfa2V5X2Zvcl9kZXZlbG9wbWVudA==" # Default: a_super_secret_key_for_development
  google_api_key: "YOUR_API_KEY_ENCODED_IN_BASE64"
